[package]
name = "nvngx-finder"
version = "0.3.0"
license = "ISC"
edition = "2021"
exclude = ["index.node"]

[dependencies]
libc = "0.2.140"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]

[profile.release]
strip=true

[lib]
crate-type = ["cdylib"]
