name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt update && sudo apt install -y cargo
      - name: Build on Linux
        run: cargo build --release
      - name: Upload linux binary
        uses: actions/upload-artifact@v2
        with:
            name: amd64-binary
            path: target/release/nvngx_finder
            retention-days: 30
